### ISSUE TITLE
Multiple select and single select drop-downs with search functionality

### ISSUE THREAD

**Issue by juliuskittler** [emdgroup-liquid/liquid#271] opened 2022-02-03 08:12 UTC
Currently, there are a variety of different drop-downs (e.g. for single select and multiple select): https://emdgroup-liquid.github.io/liquid/components/ld-select/

However, these drop-downs may not be user friendly when there is a very large number of options to select from (e.g. more than hundred) because then the user would have to scroll around for a while until the right element is found in the drop-down.

**Describe the solution you'd like**

It would be great if you could provide a drop-down with search functionality which allows to search for specific items (in addition to scrolling through the selectable items). For instance, you could then search for a specific element and then select from the search results the actual element you are looking for. 

This option should exist for both the single select and the multiple select dropdown.

Examples: 
- https://www.w3schools.com/howto/howto_js_filter_dropdown.asp
- https://select2.org/getting-started/basic-usage

**Comment by borisdiakur** [comment] 2022-02-03 09:12
Hi @juliuskittler 👋 This seems to be a duplicate of https://github.com/emdgroup-liquid/liquid/issues/238 👯‍♀️ Please vote up. I will close this one for now.

PS: Please note that the `ld-select` component has a typeahead feature. So, as a user you don't have to scroll all the way down. You can type something and the corresponding option is scrolled to automatically. However, I understand that this is not obvious and not the same as a search.

**Closed by borisdiakur** 2022-02-03 09:12 UTC
